# Site settings
title: Captures By Cayla
email: cayla@capturesbycayla.com
description: > # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ut erat odio. Maecenas suscipit fermentum enim et sagittis. Vivamus ut massa porttitor, ornare risus in, cursus tellus. Pellentesque ultricies vitae urna eu blandit. Nam consectetur auctor dolor, imperdiet convallis augue fringilla vitae. Etiam et enim a erat molestie volutpat. Proin sed euismod mi.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://capturesbycayla.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
