# Site settings
title: Captures By Cayla
email: contact@example.com
description: > # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum tenetur repellendus,
  nisi quas sunt possimus, dolore accusantium facilis ut aspernatur eligendi vero deleniti.<br>
  Quia aperiam earum, reiciendis consequatur magnam animi.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://rockhopper72.github.io/capturesbycayla.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
